Try a recovery procedure on failed vagrant destroys with libvirt
This happens on seemingly innocuous cancel pipeline clicks, as nothing
seems to run the after_script to clean these up in that case, cf.
https://gitlab.com/gitlab-org/gitlab/-/issues/15603

The remediation won't necessarily work, but we can at least try, using the
slightly different host name pattern used by vagrant-libvirt, and likewise
the libvirt URI connection qemu:///system (the latter needs to be explicit
as automatic virsh URI resolution doesn't work with non-root users like
gitlab-runner where the default libvirt URI connection is qemu:///session)

We try a virsh destroy (vagrant destroy might have failed for unrelated
reasons) and then use its undefine action with a parameter for also dropping
all storage (so we don't need another vol-delete)

diff --git a/.vagrant-jobs.gitlab-ci.yml b/.vagrant-jobs.gitlab-ci.yml
--- a/.vagrant-jobs.gitlab-ci.yml
+++ b/.vagrant-jobs.gitlab-ci.yml
@@ -34,8 +34,18 @@
       else
         vagrant box add --provider $VAGRANT_PROVIDER $VAGRANT_BOX
       fi
+      if ! vagrant destroy $TEST_HOST -f; then
+        if [ "$VAGRANT_PROVIDER" = "libvirt" ]; then
+          libvirt_vm=ansible-playbooks_$TEST_HOST
+          export LIBVIRT_DEFAULT_URI="qemu:///system"
+          virsh destroy $libvirt_vm || true
+          virsh undefine $libvirt_vm --remove-all-storage
+        else
+          echo "Aiee, $TEST_HOST could not be destroyed in $VAGRANT_PROVIDER"
+          exit 1
+        fi
+      fi
       set +x
-    - "vagrant destroy $TEST_HOST -f || true"
     - |
       if [ -n "$VAGRANT_BOX_NEEDS_CHECKED_OUT_BRANCH" ]; then
          echo "Box |$VAGRANT_BOX_NEEDS_CHECKED_OUT_BRANCH| needs a branch"
